### ISSUE TITLE
[Mechanics] thrower motor too high

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#15]
The motor seems too high compared to ball height. The ball might not touch the motor correctly

**Comment by marcanderetti** [comment]
Awesome. The motor height was determined by instructors in the classroom

**Comment by Akustav** [comment]
@maidlam @ReikoR WDYT? 
![image](https://user-images.githubusercontent.com/5435954/193650932-fd8f2eee-a1b7-49b2-b9e5-b76bf3138c74.png)

**Comment by maidlam** [comment]
Me and @ReikoR added these lines, one of them signifying the ground (on the right in the image, other line is on the bottom of the plate), into the assembly during a practical. I can't recall, if it accounted for sinking into the carpet.
The distance to the center of the motor from the bottom line is 55,115 mm, so 41,115 mm should be from the bottom of the motor to the ground.
Since a rubber tube or other soft material is planned to be added to the thrower motor, I think it will add enough thickness, so a ball can be grabbed.

![pilt](https://user-images.githubusercontent.com/32770145/193803211-ee1c2d92-94bf-4103-abbd-6f28d8304cbd.png)

**Comment by Akustav** [comment]
Okay. With the rubber pay mind not to use too soft material that can deform in with high motor rotation speeds.
